version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
